[env:xplained_mini]
platform = atmelavr
board = atmega328p_xplained_mini
framework = arduino
monitor_speed = 9600

; Optiuni suplimentare pentru compilator (ajuta la avertismente si cod mai curat)
build_flags =
  -Wall
  -Wextra
  -Os
